### ISSUE TITLE
Output is multiple line in transcript

### ISSUE THREAD

**Issue by fabricesemti80** [EvotecIT/PSWriteColor#8]
Hi !

This module is amazing and I use it in a few of my recent scripts. 
I have one question though (not a huge problem I suppose):

When I use this within a script...
![image](https://user-images.githubusercontent.com/37410363/105031315-0f439100-5a4d-11eb-8f42-c12fcdc286cc.png)

...the console output is as intended...
![image](https://user-images.githubusercontent.com/37410363/105031941-f38cba80-5a4d-11eb-8dd1-ff906fb8758d.png)

...but if the script is transcripted, the transcript results in line breaks for each color. 
![image](https://user-images.githubusercontent.com/37410363/105031270-fb982a80-5a4c-11eb-88ca-2688e6f58c5b.png)

Is there any way to add a switch that prevents this?

**Comment by PrzemyslawKlys** [comment]
This behavior is by design for a simple reason. Write-Color is a wrapper against Write-Host. This means for every new color on same line Write-Host is used. 

For example:

```powershell
Write-Host -Object 'Test' -ForegroundColor Red -NoNewline
Write-Host -Object ' test2' -ForegroundColor Yellow
```

This will give you same thing as `Write-Color -Text 'Test',' test2' -Color Red, Yellow`. 

What you can do is use built-in transcript functionality into write-color `Write-Color -LogFile YourPath -Color -...` this will mean it will display stuff as it would and save the same line (without colors) to text file.

**Comment by fabricesemti80** [comment]
That is great, thanks. Overlooked that parameter somehow.
